from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from shared.domain.entities.document import Document
from shared.domain.entities.risk_assessment import RiskAssessment
from shared.domain.entities.user import User
from shared.domain.enums import DocumentStatus


@runtime_checkable  # enables isinstance() checks
class UserRepository(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def exists_by_email(self, email: str) -> bool: ...


@runtime_checkable  # enables isinstance() checks
class DocumentRepository(Protocol):
    async def get(self, document_id: UUID) -> Document | None: ...
    async def get_by_client(
        self, client_id: UUID, *, status: DocumentStatus | None = None
    ) -> list[Document]: ...
    async def get_all(self, *, limit: int = 50, offset: int = 0) -> list[Document]: ...
    async def save(self, document: Document) -> Document: ...
    async def count(self) -> int: ...
    async def delete(self, document_id: UUID) -> bool: ...


@runtime_checkable
class RiskAssessmentRepository(Protocol):
    async def get(self, riskassessment_id: UUID) -> RiskAssessment | None: ...
    async def get_by_client(self, client_id: UUID) -> list[RiskAssessment]: ...
    async def save(self, assessment: RiskAssessment) -> RiskAssessment: ...
    async def get_latest_for_client(self, client_id: UUID) -> RiskAssessment | None: ...
